### ISSUE TITLE
Deposit Data in UA Libraries Data Repo

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#62]

**Comment by MagicMilly** [comment]
- [ ] Metadata for all data products
- [ ] README.txt required by the library
- [ ] Authors
- [ ] License
- [ ] Abstract
- [ ] Description
- [ ] Citation
- [ ] Scripts for pulling data
 - start with [David's script](https://github.com/terraref/data-publication/blob/master/code/s4s6_sql2csv.R)
- [ ] Scripts for cleaning data
 - Can also include notebooks within Data Repo and can convert notebooks to scripts as well
- [ ] Visualizations
- [ ] Include ontologies and cultivar lists?
- [ ] possibly workflow automation

**Comment by MagicMilly** [comment]
Closing this since all related issues are closed, and we decided to house the derived datasets on GitHub and CyVerse.
