### ISSUE TITLE
Create new Cookie Cutter data science project

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#71]
Following this [guide](https://drivendata.github.io/cookiecutter-data-science/#getting-started), create a new repo for data publication using Cookie Cutter. 

**Overall Goals for New Repo**
- to keep code, data, and other materials in one place so that it's easy for collaborators and others to find
- have project directory, folders, and files ready for data publication

**Action Steps to Complete this Ticket**
- [x] create new repo as Cookie Cutter Data Science project
- [x] add notebooks for data cleaning code
- [x] include David's script for pulling data
- [x] ensure all derived datasets are updated and commit (larger data like raw datasets pulled from betydb can link to a CyVerse download or Google Drive)
- [ ] write README to include metadata, description of project, explanation of folder structure
- [x] for more detailed metadata (i.e. methods), direct users to relevant markdown file or link to protocols.io
- [x] share with collaborators for review

**Comment by MagicMilly** [comment]
new for-data-publication [repo](https://github.com/MagicMilly/for-data-publication)

**Comment by MagicMilly** [comment]
- Have added mac seasons 4 and 6 and clemson data cleaning [notebooks](https://github.com/MagicMilly/for-data-publication/tree/master/notebooks)

- Have added all derived [datasets](https://github.com/MagicMilly/for-data-publication/tree/master/data/processed) for mac seasons 4 and 6 and clemson

- Included automatic download links to raw data on CyVerse for mac seasons 4 and 6 and clemson in [README](https://github.com/MagicMilly/for-data-publication/blob/master/README.md)

- Need to update and add Kansas data (link to raw data, cleaning notebook, and derived datasets) once SSL certificate problems are resolved

**Comment by MagicMilly** [comment]
- Added KSU cleaning [notebook](https://github.com/MagicMilly/for-data-publication/tree/master/notebooks)
- Added derived KSU [datasets](https://github.com/MagicMilly/for-data-publication/tree/master/data/processed) to GitHub and Google [drive](https://drive.google.com/drive/folders/19o-c-QnNQAsKpYUdoU7Khs5D2Xl0HIVi?usp=sharing)
- Added links to raw data on CyVerse
  - Ashland Bottoms Weather [Data](https://de.cyverse.org/dl/d/7DDD1490-C380-4512-96E9-FE7E24251506/ashland_bottoms_daily_weather_2016.csv) for 2016
  - KSU Season 6 trait [data](https://de.cyverse.org/dl/d/018B11DA-28E7-46B8-88D9-4481904FFBA7/ksu_data_2020-06-11.csv)

**Comment by MagicMilly** [comment]
The remaining task needed to complete this ticket is to finish describing changes made to the raw data to create the processed data products, which is addressed in new ticket #84
