### ISSUE TITLE
Become familiar with NEON / NPN data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#74]
**Tasks**
- [x] Explore data using Shiny app on the DE

@rbartelme specifically suggested looking for sites with:
 - [ ] metabarcodes for macrofauna
 - [x] soil metagenome
 - [x] more than one metagenome
 - [ ] covariates for evotranspiration
 - [x] covariates shared with TERRA-REF data

**Expected Outcomes**
- Be able to list sites with the above criteria
- Be able to interact with NEON data beyond the Shiny GUI app

**Comment by MagicMilly** [comment]
Google sheet [started](https://docs.google.com/spreadsheets/d/1RFBirlPtoZJzdIoYTTOemO2olg3u85VQyCfu-Hspdas/edit?usp=sharing) which will contain sites and their available data

**Comment by MagicMilly** [comment]
Google [sheet](https://docs.google.com/spreadsheets/d/1RFBirlPtoZJzdIoYTTOemO2olg3u85VQyCfu-Hspdas/edit?usp=sharing) containing sites with 3 or more soil metagenome sequences with boolean columns indicating which sites also have (somewhat arbitrarily) associated data products. Every NEON site (including the 20 selected by soil metagenome) contained the selected data products except for `soil microbe community composition`. 

I am also not sure that the associated data products included in the Google sheet include _all_ covariates for evotranspiration, so that will need to be reviewed specifically, or I can work from a list of these covariates. 

Should the associated data products be filtered by another variable (i.e. year) to be more useful?  

These questions and related follow-up tasks will be addressed in Issue #78 for next Sprint.
